name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.SERVER_HOST}}
            username: ${{secrets.SERVER_USERNAME}}
            password: ${{secrets.SERVER_PASSWORD}}
            port: ${{secrets.SERVER_PORT}}
            script: |
                cd /var/www/html/
                git pull origin main
                git status
                npm install 
