name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.SERVER_HOST}}
            username: ${{secrets.SERVER_USERNAME}}
            password: ${{secrets.SERVER_PASSWORD}}
            port: ${{secrets.SERVER_PORT}}
            script: |
                # Masuk ke direktori target
                cd /var/www/html/ || { echo "Failed to cd into /var/www/html/"; exit 1; }

                # Pastikan direktori adalah repositori Git
                if [ ! -d ".git" ]; then
                    echo "Initializing new git repository"
                    git init || { echo "Failed to initialize git repository"; exit 1; }
                    git remote add origin https://github.com/SelarasHomeId/Frontend.git || { echo "Failed to add remote origin"; exit 1; }
                fi
                
                # Pull dari repositori
                git pull origin main || { echo "Failed to pull from origin"; exit 1; }
                
                # Periksa status git
                git status || { echo "Failed to check git status"; exit 1; }
                
                # Periksa dan instal npm jika belum terinstal
                if ! command -v npm &> /dev/null; then
                    echo "npm not found, installing npm"
                    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - || { echo "Failed to download NodeSource setup script"; exit 1; }
                    sudo apt-get install -y nodejs || { echo "Failed to install nodejs"; exit 1; }
                fi
                
                # Instal dependensi npm
                npm install --only=prod || { echo "npm install failed"; exit 1; }